<a href="https://colab.research.google.com/github/adityachoudharyclg/pytorchBasics/blob/master/Logistic_regression_using_pytorch_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torchvision
from torchvision.datasets import MNIST
import torchvision.transforms as transforms

In [0]:
dataset = MNIST(root='data/', 
                train=True,
                transform=transforms.ToTensor(),download=True)

In [0]:
test_dataset=MNIST(root='data/', 
                train=False,
                transform=transforms.ToTensor())

In [4]:
len(test_dataset)

10000

In [0]:
# For splitting data
from torch.utils.data import random_split
train_ds,val_ds=random_split(dataset,[50000,10000])

In [0]:
# Loading data
from torch.utils.data import DataLoader
train_loader=DataLoader(train_ds,batch_size=256,shuffle=True)
val_loader=DataLoader(val_ds,batch_size=256)

In [7]:
for xb,yb in train_loader:
  print(xb.shape)
  break

torch.Size([256, 1, 28, 28])


In [0]:
import torch.nn as nn

In [0]:
input_size=28*28
num_classes=10
model=nn.Linear(input_size,num_classes)

In [10]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0034,  0.0141,  0.0047,  ...,  0.0257, -0.0086, -0.0223],
         [ 0.0314, -0.0155, -0.0005,  ...,  0.0212, -0.0030, -0.0020],
         [ 0.0031, -0.0126,  0.0039,  ...,  0.0343, -0.0326,  0.0116],
         ...,
         [-0.0254, -0.0204,  0.0070,  ...,  0.0205,  0.0005,  0.0073],
         [ 0.0049,  0.0290,  0.0263,  ...,  0.0121,  0.0325, -0.0127],
         [ 0.0139,  0.0185,  0.0053,  ...,  0.0133, -0.0200, -0.0086]],
        requires_grad=True), Parameter containing:
 tensor([ 0.0264, -0.0301,  0.0125, -0.0070, -0.0073,  0.0101, -0.0349, -0.0103,
          0.0060,  0.0002], requires_grad=True)]

In [11]:
# O/P function
import torch.nn.functional as F

for tensor,label in val_loader:
  tensor=tensor.reshape(-1,784)
  print(tensor.shape)
  outputs=model(tensor)
  break

probs=F.softmax(outputs,dim=1)
print(probs)
print("Sum:",torch.sum(probs[0]).item())

torch.Size([256, 784])
tensor([[0.1142, 0.1048, 0.0779,  ..., 0.1113, 0.0982, 0.0803],
        [0.0903, 0.0802, 0.0659,  ..., 0.1149, 0.1171, 0.0846],
        [0.1012, 0.1225, 0.0527,  ..., 0.0998, 0.1001, 0.0715],
        ...,
        [0.1033, 0.1166, 0.0926,  ..., 0.0991, 0.0960, 0.0927],
        [0.0866, 0.1142, 0.0734,  ..., 0.0916, 0.0839, 0.0975],
        [0.1024, 0.1035, 0.0729,  ..., 0.0996, 0.0883, 0.0920]],
       grad_fn=<SoftmaxBackward>)
Sum: 0.9999998807907104


In [12]:
max_probs,preds=torch.max(probs,dim=1)
print(preds)
print(max_probs)

tensor([3, 5, 5, 8, 6, 3, 0, 5, 0, 7, 5, 7, 5, 6, 1, 4, 7, 7, 7, 7, 6, 9, 5, 0,
        3, 5, 1, 3, 1, 7, 6, 5, 1, 5, 1, 6, 4, 5, 5, 7, 5, 7, 7, 5, 5, 5, 8, 5,
        5, 5, 0, 6, 5, 5, 1, 5, 3, 5, 3, 1, 3, 5, 3, 3, 5, 5, 7, 5, 5, 7, 9, 6,
        4, 1, 0, 1, 6, 4, 7, 7, 7, 7, 5, 6, 7, 3, 8, 5, 5, 3, 7, 5, 7, 3, 7, 1,
        3, 5, 5, 1, 7, 0, 7, 3, 6, 3, 7, 8, 7, 7, 7, 7, 3, 6, 3, 4, 3, 7, 1, 6,
        7, 7, 7, 7, 7, 7, 3, 6, 5, 7, 5, 5, 8, 1, 5, 6, 7, 1, 6, 5, 8, 7, 3, 7,
        4, 7, 1, 6, 3, 5, 1, 0, 7, 7, 4, 4, 3, 5, 7, 5, 5, 1, 5, 6, 5, 5, 5, 6,
        7, 7, 3, 4, 3, 5, 4, 5, 4, 3, 6, 4, 6, 7, 3, 1, 4, 4, 3, 1, 5, 1, 7, 4,
        7, 7, 1, 6, 3, 0, 5, 3, 5, 6, 4, 1, 6, 4, 6, 5, 4, 5, 5, 5, 0, 7, 3, 4,
        7, 3, 6, 7, 0, 6, 5, 1, 6, 7, 1, 7, 7, 8, 5, 5, 4, 5, 3, 7, 7, 5, 3, 5,
        3, 7, 3, 0, 5, 1, 1, 5, 6, 5, 5, 7, 1, 1, 5, 5])
tensor([0.1197, 0.1590, 0.1557, 0.1129, 0.1408, 0.1204, 0.1146, 0.1115, 0.1206,
        0.1366, 0.1447, 0.1367, 0.1298, 0.1208, 0.1260, 0.1208,

In [0]:
def accuracy(outputs,labels):
  _,preds=torch.max(outputs,dim=1)
  return torch.tensor(torch.sum(preds==labels).item()/len(preds))

In [14]:
accuracy(outputs,label)

tensor(0.1133)

In [0]:
# Loss function
loss_fn=F.cross_entropy

In [16]:
print(outputs,outputs.shape)
print(label,label.shape)
loss=loss_fn(outputs,label)
print(loss)

tensor([[ 0.2092,  0.1236, -0.1734,  ...,  0.1839,  0.0584, -0.1425],
        [-0.1456, -0.2644, -0.4601,  ...,  0.0949,  0.1142, -0.2104],
        [ 0.1453,  0.3361, -0.5066,  ...,  0.1310,  0.1336, -0.2026],
        ...,
        [-0.0035,  0.1177, -0.1128,  ..., -0.0452, -0.0769, -0.1118],
        [-0.0568,  0.2202, -0.2220,  ..., -0.0007, -0.0888,  0.0623],
        [ 0.1314,  0.1424, -0.2075,  ...,  0.1038, -0.0166,  0.0249]],
       grad_fn=<AddmmBackward>) torch.Size([256, 10])
tensor([6, 3, 3, 6, 2, 4, 1, 1, 6, 9, 8, 9, 3, 2, 6, 7, 8, 4, 6, 9, 5, 9, 3, 5,
        3, 5, 0, 9, 6, 0, 2, 7, 2, 5, 0, 9, 1, 3, 7, 2, 4, 0, 7, 4, 7, 7, 7, 3,
        5, 8, 7, 9, 3, 3, 8, 2, 7, 3, 5, 3, 0, 4, 8, 8, 5, 1, 3, 3, 0, 9, 9, 3,
        8, 8, 7, 1, 2, 1, 4, 9, 0, 4, 5, 2, 6, 8, 8, 3, 9, 8, 3, 3, 2, 3, 2, 6,
        9, 3, 9, 9, 4, 6, 5, 6, 5, 7, 4, 7, 6, 9, 8, 6, 5, 8, 0, 7, 1, 0, 6, 2,
        9, 0, 4, 9, 5, 7, 9, 1, 9, 0, 3, 5, 7, 1, 4, 3, 2, 2, 5, 6, 7, 2, 5, 4,
        1, 0, 8, 6, 7, 2, 2, 9, 

In [0]:
# Creating our model
class MnistModel(nn.Module):
    def __init__(self,input_size=784,num_classes=10):
        super().__init__()
        self.linear=nn.Linear(input_size,num_classes)
        self.input_size=input_size
        self.num_classes=num_classes
    
    def forward(self,xb):
        xb=xb.reshape(-1,self.input_size)
        out=self.linear(xb)
        return out

    def predictions(self,inputs):
        outputs=self(inputs)
        _,preds=torch.max(outputs,dim=1)
        return preds
    
    def loss_func(self,outputs,labels):
        lossFunc=F.cross_entropy
        loss=lossFunc(outputs,labels)
        return loss
    
    def accuracy(self,outputs,labels):
        _,preds=torch.max(outputs,dim=1)
        return torch.tensor(torch.sum(preds==labels).item()/len(preds))
    
    def fit(self,train_loader,val_loader,learning_rate=1e-3,num_epochs=10):
        opt_func=torch.optim.SGD
        optimizer=opt_func(self.parameters(),learning_rate)
        for epoch in range(num_epochs):
            # Training phase
            for batch,labels in train_loader:
                # Generate predictions
                preds=self.predictions(batch)
                # Calculate loss
                loss=self.loss_func(self(batch),labels)
                # Compute gradients
                loss.backward()
                # Update weights
                optimizer.step()
                # Reset gradients
                optimizer.zero_grad()
            
            # Validation phase
            for batch,labels in val_loader:
                # Calculate loss
                val_loss=self.loss_func(self(batch),labels)
                # Calculate metrics (accuracy etc.)
                val_acc=self.accuracy(self(batch),labels)
            # Calculate average validation loss & metrics
            
            # Log epoch, loss & metrics for inspection
            print("Epoch [{}/{}]: training_loss:{} val_loss:{} val_acc:{}".format(epoch+1,num_epochs,loss,val_loss,val_acc))

In [18]:
model=MnistModel()
for tensors,labels in train_loader:
    outputs=model(tensors)
    print(model.predictions(tensors).shape)
    # print(model.predictions(tensors),labels,labels.shape)
    print(model.loss_func(outputs,labels))
    break

torch.Size([256])
tensor(2.2825, grad_fn=<NllLossBackward>)


In [19]:
model=MnistModel()
model.fit(train_loader,val_loader)

Epoch [1/10]: training_loss:2.0976905822753906 val_loss:2.0302674770355225 val_acc:0.4375
Epoch [2/10]: training_loss:1.9231141805648804 val_loss:1.836472511291504 val_acc:0.6875
Epoch [3/10]: training_loss:1.7899360656738281 val_loss:1.6791718006134033 val_acc:0.8125
Epoch [4/10]: training_loss:1.6092002391815186 val_loss:1.5507121086120605 val_acc:0.875
Epoch [5/10]: training_loss:1.616206169128418 val_loss:1.4418944120407104 val_acc:0.875
Epoch [6/10]: training_loss:1.4314583539962769 val_loss:1.349196195602417 val_acc:0.9375
Epoch [7/10]: training_loss:1.3610963821411133 val_loss:1.2689852714538574 val_acc:0.9375
Epoch [8/10]: training_loss:1.397282361984253 val_loss:1.2000732421875 val_acc:0.9375
Epoch [9/10]: training_loss:1.1639893054962158 val_loss:1.138959288597107 val_acc:0.9375
Epoch [10/10]: training_loss:1.1818493604660034 val_loss:1.0857354402542114 val_acc:0.9375


In [0]:
test_loader = DataLoader(test_dataset, batch_size=1024,shuffle=True)

In [21]:
for batch,labels in test_loader:
    outputs=model(batch)
    print(model.accuracy(outputs,labels))

tensor(0.8066)
tensor(0.7891)
tensor(0.7881)
tensor(0.8076)
tensor(0.8223)
tensor(0.8037)
tensor(0.7881)
tensor(0.8086)
tensor(0.7979)
tensor(0.8074)


Saving and loading model

In [0]:
torch.save(model.state_dict(), 'mnist-logistic.pth')

In [23]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.0268,  0.0080,  0.0026,  ..., -0.0208,  0.0218,  0.0320],
                      [ 0.0155, -0.0259, -0.0220,  ..., -0.0042, -0.0157, -0.0138],
                      [ 0.0338, -0.0210,  0.0151,  ..., -0.0036, -0.0123,  0.0329],
                      ...,
                      [-0.0254,  0.0350, -0.0345,  ...,  0.0065,  0.0355,  0.0218],
                      [-0.0170, -0.0249, -0.0307,  ..., -0.0035, -0.0244,  0.0133],
                      [-0.0345, -0.0149, -0.0307,  ...,  0.0337, -0.0264,  0.0279]])),
             ('linear.bias',
              tensor([-0.0167,  0.0139, -0.0369, -0.0074,  0.0242,  0.0306, -0.0216, -0.0136,
                      -0.0098,  0.0220]))])

In [24]:
model2 = MnistModel()
model2.load_state_dict(torch.load('mnist-logistic.pth'))
model2.state_dict()

OrderedDict([('linear.weight',
              tensor([[-0.0268,  0.0080,  0.0026,  ..., -0.0208,  0.0218,  0.0320],
                      [ 0.0155, -0.0259, -0.0220,  ..., -0.0042, -0.0157, -0.0138],
                      [ 0.0338, -0.0210,  0.0151,  ..., -0.0036, -0.0123,  0.0329],
                      ...,
                      [-0.0254,  0.0350, -0.0345,  ...,  0.0065,  0.0355,  0.0218],
                      [-0.0170, -0.0249, -0.0307,  ..., -0.0035, -0.0244,  0.0133],
                      [-0.0345, -0.0149, -0.0307,  ...,  0.0337, -0.0264,  0.0279]])),
             ('linear.bias',
              tensor([-0.0167,  0.0139, -0.0369, -0.0074,  0.0242,  0.0306, -0.0216, -0.0136,
                      -0.0098,  0.0220]))])

In [25]:
for batch,labels in test_loader:
    outputs=model(batch)
    print(model.accuracy(outputs,labels))

tensor(0.8018)
tensor(0.7988)
tensor(0.8174)
tensor(0.7959)
tensor(0.8027)
tensor(0.8027)
tensor(0.8027)
tensor(0.7842)
tensor(0.8115)
tensor(0.7997)
