<a href="https://colab.research.google.com/github/adityachoudharyclg/pytorchBasics/blob/master/Pytorch_Basics(Tensors_and_gradients).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
t1=torch.tensor(4.)

In [7]:
print(t1)
print(t1.shape)

tensor(4.)
torch.Size([])


In [8]:
t1=torch.tensor([1,2,3,4])
t2=torch.tensor([[0 for i in range(3)] for i in range(3)])
print(t1.shape,t2.shape)

torch.Size([4]) torch.Size([3, 3])


Tensor operations and gradients

In [9]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [10]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [0]:
y.backward()

In [13]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Interoperability with numpy

In [0]:
import numpy as np

In [16]:
# numpy to torch tensor
data=np.ones((2,3))
temp=torch.from_numpy(data)
print(temp)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [17]:
# torch tensor to numpy
temp=temp.numpy()
print(temp)

[[1. 1. 1.]
 [1. 1. 1.]]
